version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:8080"
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
