version: "3.8"
services:
  1up-dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3007:8080" 
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
